name: Deploy to Surge

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Verify Node.js installation
      run: node --version

    - name: Install Surge
      run: npm install --global surge

    - name: Login to Surge
      run: surge --login

    - name: Deploy to Surge
      run: surge --project ./ --domain jeffry-de-jesus.surge.sh
